<?php
/**
 * @var Detail $block
 */

use Training\Blog\Block\Detail;

$blog = $block->getBlogById();
$tags = $block->getTags();
$products = $block->getProductById(json_decode($blog['product_ids']));

?>

<style>
    .container .header-page {
        display: flex;
    }
    .container .header-page .left-container {
        width: 250px;
        height: 300px;
    }
    .container .header-page .left-container img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
    .container .header-page .right-container {
        padding: 0 20px;
        width: 50%;
    }
    .container .header-page .right-container .list-tag {
        display: flex;
        flex-direction: row;
    }
    .container .header-page .right-container .list-tag .tag-item {
        background: #f0f0f0;
        border-radius: 3px;
        margin-right: 3px;
        padding: 0 8px;
    }
    .short-description {
        margin-top: 15px;
    }
    .image-product {
        height: 250px;
        object-fit: cover;
    }
    .gallery img {
        width: 250px;
        height: 300px;
        object-fit: cover;
        margin-right: 10px;
        border-radius: 3px;
    }
</style>

<?php
if (count($blog) > 0)
{
?>
<input type="hidden" id="number-product" value="<?php echo count($products); ?>" />
<div class="container">
    <div class="header-page">
        <div class="left-container">
            <img src="<?php echo '/media/blog/images/' .$blog['thumbnail'] ?>"/>
        </div>
        <div class="right-container">
            <h2><?php echo $blog['name']; ?></h2>
            <div class="list-tag">
                <?php
                    $tagOfBlog = json_decode($blog['tags']);
                    foreach ($tags as $tag) {
                        foreach ($tagOfBlog as $item) {
                            if ((int) $tag['tag_id'] == (int) $item) {
                                echo '<div class="tag-item">#' . $tag['name'] . '</div>';
                            }
                        }
                    }
                ?>
            </div>
            <div class="short-description">
                <?php
                    echo $blog['short_description'];
                ?>
            </div>
        </div>
    </div>

    <hr>
    <div>
        <h3>Gallery: </h3>
        <div class="gallery">
            <?php
                foreach (json_decode($blog['gallery']) as $gallery) {
                    echo '<img  src="/media/blog/images/' . $gallery . '"/>';
                }
            ?>
        </div>
        <div>
            <h3>Description: </h3>
        </div>
        <?php echo $blog['description'] ?>
        <div>
            <h3>Related Products</h3>
        </div>
        <div class="owl-carousel owl-theme">
            <?php
            foreach ($products as $product) {
                echo '
                <div class="item">
                    <img class="image-product"
                        src="' . (isset($product['image']) ? "/media/catalog/product" . $product['image'] : "https://www.madeireiraestrela.com.br/images/joomlart/demo/default.jpg") . '">
                    <h3>' . ($product['name'] ?? "") . '</h3>
                    <h4>$' . ($product['price'] ?? 0) . '</h4>
                </div>
            ';
            }
            ?>
        </div>
    </div>
</div>
    <script>
        require([
            'jquery'
        ], function ($) {
            $(function () {
                setTimeout(() => {
                    const numberItem = document.getElementById('number-product').value
                    const countItems = numberItem <= 3 ? numberItem : 3
                    $('.owl-carousel').owlCarousel({
                        loop:true,
                        margin:10,
                        nav:true,
                        items:3,
                        autoplay: true,
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:countItems
                            }
                        }
                    })
                }, 1000)
            });
        });
    </script>
<?php
} else {
?>
No Data

<?php
}
?>
